### ISSUE TITLE
Option to set effort when converting to avif

### ISSUE THREAD

**Issue by rohitghali** [gen2brain/cbconvert#11]
How do I set effort when converting files to avif?

**Comment by gen2brain** [comment]
You can't, you can only set `quality` effort and `lossless` options, as per libheif docs https://pkg.go.dev/github.com/strukturag/libheif@v1.14.0/go/heif#EncodeFromImage.
You can see some comparisons with JPEG quality here https://www.industrialempathy.com/posts/avif-webp-quality-settings/.

**Comment by rohitghali** [comment]
![image](https://user-images.githubusercontent.com/42379398/206498295-aee0a2fc-b15f-4356-9983-83ba4f8b875b.png)
Like in the image above. What's the effort option there?

**Comment by gen2brain** [comment]
There is no option. Libheif doesn't expose that option, everything is done with quality.

**Comment by rohitghali** [comment]
ok.
