### ISSUE TITLE
Case-insensitive sort

### ISSUE THREAD

**Issue by chowbok** [gen2brain/cbconvert#13]
I have a CBR file that has files with the following names:

- showcase020_p_001.jpg
- showcase020_p_002.jpg
- (etc.)
- XXX_Shadow_final.jpg

cbconvert is showing "XXX_Shadow_final.jpg" as the thumb, but "showcase020_p_001.jpg" is the correct one. I assume this is because the "X" is capitalized. Can it be changed to do case-insensitive sorting for the purposes of picking a thumbnail?

**Comment by gen2brain** [comment]
`coverName` is using the "natural" sort, I guess I can lowercase all images before sorting and picking the cover but needs to test on a large sample first. Just checked in "mc" which sorts similarly, XXX is the first/top file.

**Comment by gen2brain** [comment]
This should be fixed in https://github.com/gen2brain/cbconvert/commit/d6e7248112f679842d255e0908fdb4a1014e4dec.
