### ISSUE TITLE
Error while converting jpeg to avif.

### ISSUE THREAD

**Issue by rohitghali** [gen2brain/cbconvert#15]
convertArchive: decodeImage: 0106.jpg: invalid JPEG format: short Huffman data

**Comment by gen2brain** [comment]
Added ImageMagick fallback for broken images in https://github.com/gen2brain/cbconvert/commit/9a047d19777e06200f33289e18fdbfd2c318b870. This should work for shared binary, static binary from releases has an issue https://github.com/gen2brain/cbconvert/issues/16.

**Comment by rohitghali** [comment]
Nope. Still getting the same error after updating to 0.8.1

`convertArchive: decodeImage: 109.jpg: invalid JPEG format: short Huffman data`

**Comment by gen2brain** [comment]
Sorry, please try with 0.8.2.
