### ISSUE TITLE
Possibility to remove the ComicInfo.xml

### ISSUE THREAD

**Issue by JohnCytron** [gen2brain/cbconvert#17]
The purpose of the `ComicInfo.xml` file is to contain the metadata of the comic. But for some reason, it can be outdated or simply wrong.
Nowadays, there are much better solutions to manage the data of our collection (Komga, Kavita, Codex...).

In order to unify and clean my collection, I plan to convert all my collection to `.cbz`. And for this purpose, your tool is perfect. It would be neat to get rid of the `ComicInfo.xml` by the same action for the reasons I mentioned earlier.

**Comment by gen2brain** [comment]
You can use the option
```
        --no-nonimage
            Remove non-image files from the archive (default "false")
```
That should remove all non-image though.

As there are so many such standards, I planned to add a new subcommand `meta` or `metadata`, with just options to add files to archive or add file contents to zip comments as some do, and some options to print a cover name. So, with some XML templates, it should be easy to script something that can manage the whole collection. Maybe then I can add support for specific filenames to be removed etc.

**Comment by JohnCytron** [comment]
Sorry I miss this command. Thanks for your quick answer, it should do the job perfectly. From my side, the issue can be close.

Speaking about your suggestion, it can be handy. I personally don't have the need, but I'm sure it would be useful for others.

**Comment by Cducharme84** [comment]
> The purpose of the `ComicInfo.xml` file is to contain the metadata of the comic. But for some reason, it can be outdated or simply wrong. Nowadays, there are much better solutions to manage the data of our collection (Komga, Kavita, Codex...).
> 
> In order to unify and clean my collection, I plan to convert all my collection to `.cbz`. And for this purpose, your tool is perfect. It would be neat to get rid of the `ComicInfo.xml` by the same action for the reasons I mentioned earlier.

 I know this issue is closed but I caution against this, Kavita has significant reliance on ComicInfo.xml info unless you've manually entered in the data into Kavita's GUI/db. With the comic rework now in the nightly releases which increases the reliance on ComicInfo.xml in order to better support western comics. I can see folks going down this path possibly looking at that new library type in envy in a few more releases.

It's possibly a better solution to update the xml using comictagger or manga-manager to mirror your changes rather than throwing the baby out with the bath water?

**Comment by gen2brain** [comment]
To add, now it is possible to add/remove files from the archive, or maybe even create something in the script with templates, i.e.:
```
      meta
            CBZ metadata

        --cover
            Print cover name (default "false")
        --comment
            Print zip comment (default "false")
        --comment-body
            Set zip comment (default "")
        --file-add
            Add file to archive (default "")
        --file-remove
            Remove file(s) from archive (glob pattern, i.e. *.xml) (default "")
```
