### ISSUE TITLE
[Feature request] Extract cover with a custom format

### ISSUE THREAD

**Issue by PhilippKammann** [gen2brain/cbconvert#18]
Currently if you extract a cover with `cbconvert cover comic.cbz` you will always get a `comic.jpg`, regardless of the actual image format inside the archive.

Would be nice if you could extract the cover without converting it or setting a format with `cbconvert cover --format webp comic.cbz` for example.

**Comment by gen2brain** [comment]
Added in https://github.com/gen2brain/cbconvert/commit/64fb152c3699f189f51fd9c2171c846c5da67f9b.
