### ISSUE TITLE
can you add webp as image target format ?

### ISSUE THREAD

**Issue by sergiodobrasil** [gen2brain/cbconvert#2]

**Comment by sergiodobrasil** [comment]
ok, thx.
i will try to add the webp support on the CMD when i get some freetime.
@+

**Comment by Protektor-Desura** [comment]
I take it that webp support was never added to the CMD version?

**Comment by gen2brain** [comment]
WebP support is added and the new release is uploaded, only CLI, and defunct GUI is removed. I will probably rewrite GUI sometime. Both Linux and Windows binaries are now fully static binaries.

As for AVIF, currently, there is only an encoder library for Go (cgo bindings), and the comic book readers I am using don't have support at all.

**Comment by gen2brain** [comment]
@Protektor-Desura support for AVIF is also added, via libheif and libaom. Both Windows and Linux binaries are fully statically compiled. As for support in comic book readers, with https://github.com/novomesk/qt-avif-image-plugin I got YacReader to work. The results are impressive, 75M file is down to 30M, if I resize the comic to 1280, which I usually do, it is down to 15M! The only downside is that it is painfully slow to encode to AVIF.
