### ISSUE TITLE
What does quality option do?

### ISSUE THREAD

**Issue by rohitghali** [gen2brain/cbconvert#20]
I'm trying to convert stuff into avif. Tried with quality value 10, 90 and 100. It's the same file size and no difference in visual quality. Am I missing something? What does it even do?

**Comment by gen2brain** [comment]
It affects JPEG, WEBP, AVIF, and JXL. You have a comparison table in the README, a quality of 70 is like 56 for AVIF. As ImageMagick is used for AVIF and JXL, their conventions must be accepted, i.e. with a quality of 100 `lossless` option is enabled. For small images, you should not see immediate results in the preview, but 0 or 10 should show something, i.e. for JPEG at least. I used a quality of 50 to convert some comics to AVIF and I am very satisfied with the size/results.

**Comment by gen2brain** [comment]
The older version used libheif directly, now it is used via ImageMagick which is built with libheif, and the quality settings is applied in MagickWand the same as is for other formats.

**Comment by rohitghali** [comment]
Yep. Works in 0.9.1. Doesn't work in 1.0.0. Literally no change in quality and size. I'm using command line BTW.

**Comment by gen2brain** [comment]
This is fixed. There is no more ImageMagic.
