### ISSUE TITLE
[FR] [gui] ability to save into same directory where original files and replace original files

### ISSUE THREAD

**Issue by user9931** [gen2brain/cbconvert#25]
as title: ability to save into same directory where original files and replace original files

such a great and easy-to-use gui app, but really miss an option to just replace original files with converted ones

**Comment by gen2brain** [comment]
What happens if the original file is .cbr or .cb7?

**Comment by stuntguy3000** [comment]
To this, I'd love for a feature to have it place the output file _alongside_ the original files. This would enable the very simple bulk conversion of heaps of files at once.

**Comment by gen2brain** [comment]
Again, if the file is e.g. `.cbr`, cbconvert can place the output file alongside, if the file is `.cbz` the original will be overwritten. In both cases, replace/overwrite or alongside there are inconsistencies.

**Comment by stuntguy3000** [comment]
I'm not sure if I fully understand but I'm referring more to the _archival output_ file.

**Comment by gen2brain** [comment]
Yes, so you wish the output file to end in the source directory right?

**Comment by stuntguy3000** [comment]
Yes :)

The power to this is when you're dealing with MANY source files across MANY folders, it makes the process so much quicker.

**Comment by gen2brain** [comment]
I explained why that would be a bad option, cbconvert can output only .cbz or .cbt, so if the source file is .cbz it will be overwritten. I don't want to add the option that can destroy the user source file and that behaves differently based on source type.

**Comment by gen2brain** [comment]
Source meaning input, original file etc.

**Comment by stuntguy3000** [comment]
Right, okay - I think I've slightly misunderstood the use of this application. That reasoning sounds logical then
