### ISSUE TITLE
Unable to read MOBI

### ISSUE THREAD

**Issue by vkoechli** [gen2brain/cbconvert#29]
Hello

When trying to convert MOBI files, cbconvert returns an error message "convertDocument: fitz: cannot create context". Are there different versions of MOBI, or is MOBI support not yet implemented?

This happens with version 1.0.0 on an Intel MacBook Pro with MacOS 14.5 (Sonoma).

**Comment by gen2brain** [comment]
MOBI support is provided by MuPDF, it worked with some sample files I tested.  Probably there are some fixes in new releases. I control the repo with mupdf wrapper, just need to find the time to update all.

**Comment by gen2brain** [comment]
MuPDF is updated and MOBI files work.
