### ISSUE TITLE
Convert to CB7

### ISSUE THREAD

**Issue by Protektor-Desura** [gen2brain/cbconvert#3]
It would be nice if this allowed you to save comic books as CB7 instead of only CBZ.

**Comment by gen2brain** [comment]
There are no libraries in Go that can write 7z, even reading is a struggle. And I don't want to depend on external binaries being installed. Anyway, I don't think the gain in size will be huge and there are always comic readers that don't handle it very well or at all.

The point here is that you can, for example, convert black&white pages to 4bit BMP, you will not notice any difference and the file can be 2-3x smaller. And there are options to skip color pages or cover.
