### ISSUE TITLE
Resize only if larger

### ISSUE THREAD

**Issue by aaaaaprvdgrwwelt** [gen2brain/cbconvert#30]
Hello,

I would like to have an option that the size is only adjusted if the original size is larger than this value. If I want to have a height of 2048 px it makes little sense for me to enlarge graphics with a height of 500 px. I only want to reduce larger formats.

It would also be practical if it were possible to convert a file format only if the file does not already have this format. So only convert jpeg and png files to webp, but not webp files.

**Comment by gen2brain** [comment]
If you check the `Fit` option it should do what you want, if the original size is smaller it will not be resized.

The other thing doesn't seem very practical, so the app should check the original format, the size, and if there is some transformation applied, etc. only to skip such file (when, only when the format is the same, or if the size is same?), which adds complexity without much benefit.
