### ISSUE TITLE
feature request: Keep the original image extension

### ISSUE THREAD

**Issue by lvcabral** [gen2brain/cbconvert#35]
Currently the app is renaming `.jpg` files to `.jpeg` but some apps do expect the `.jpg` extension, so when converting the jpeg files, either keep the original extension or at least add an option to select it.

**Comment by gen2brain** [comment]
I would not go so far as to complicate it so much, `.jpeg` can just be forced to `.jpg` and that is it, no need for an option for that. I would argue that such apps are broken, who cares what is the filename or extension, there are ways to detect image type.

**Comment by gen2brain** [comment]
Addressed in https://github.com/gen2brain/cbconvert/commit/1a5520c05090371c19820a5420aa9393bad35e29. It just simply uses `.jpg` extension for the `jpeg` format, so all old `8.3` apps should work.
