### ISSUE TITLE
feature request: Add version flag for cbconvert-gui

### ISSUE THREAD

**Issue by jwillikers** [gen2brain/cbconvert#39]
Would it be possible to add a version flag for the `cbconvert-gui` application like there is for the `cbconvert` command-line utility? This will help with automatic testing of the Nix package.

Also, I have finished work for the package and just need to submit it to nixpkgs, pending this last item. Would it be possible to make a subsequent release as well?

**Comment by gen2brain** [comment]
Yes, is possible, I will add it when I find time. Sorry, the new release will happen when I finish everything I planned.

**Comment by gen2brain** [comment]
Addressed in https://github.com/gen2brain/cbconvert/commit/4f23f228a8fcee4b1cc64166bf8f327270f2665f. There will be a new release in a few days.
