### ISSUE TITLE
Maintain Dir Structure when Converting Large Dirs Recursively

### ISSUE THREAD

**Issue by cattamite** [gen2brain/cbconvert#4]
Is there a way to maintain an existing directory structure if I am processing large numbers of files and subdirs?  The Output Dir just puts everything into a single Dir regardless of the source Dir.

**Comment by gen2brain** [comment]
Sorry, I will not work on this, it would complicate a lot of things.

**Comment by gen2brain** [comment]
This is now fixed. After refactoring it was easy. Now when the recursive option is used the directory structure is preserved. Also, there is a new GUI.
