### ISSUE TITLE
Crop white border

### ISSUE THREAD

**Issue by jwillikers** [gen2brain/cbconvert#45]
When converting from EPUB to CBZ, the JPEGs end up having a white border. This is especially noticable for the cover. Would it be possible to remove this extra margin? I'd like to maximize the screen real estate on my e-reader. I found that KindleComicConverter supports this functionality along with removing pages numbers there as well.

I'm not sure if this is related, but the cover in the EPUB's metadata ends up having a higher resolution than the cover in the CBZ. It would be great if I could get the full resolution cover in the CBZ.

**Comment by gen2brain** [comment]
Is this the same as https://github.com/gen2brain/cbconvert/issues/40?

**Comment by jwillikers** [comment]
Looks like it, closing as a duplicate. Thanks!
