### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by darylf** [gen2brain/cbconvert#5]
The compile instructions include an error in the "Compile unarr library" steps

This url returns a 404 not found: http://zlib.net/zlib-1.2.8.tar.gz

**Comment by gen2brain** [comment]
You can just skip those steps. Both `go-fitz` and `go-unarr` libraries now contain everything included. Whole GUI must be rewritten so I don't bother with README.

**Comment by gen2brain** [comment]
The new release is uploaded and the README is updated.
