### ISSUE TITLE
Convert container format without modifying images

### ISSUE THREAD

**Issue by alexandernst** [gen2brain/cbconvert#7]
Is it possible to, somehow, convert from cbr to cbz (rar to zip archive) without modifying the images? I'd like to leave everything as-is, and just change the container format. 

I tried `--quality=100`, but that apparently increases the size of each image.

**Comment by gen2brain** [comment]
There is no such option, but you can try with `--no-rgb`, which will skip all files that are not grayscale, assuming all images are not actually grayscale.

**Comment by gen2brain** [comment]
I added `--no-convert` option that will just copy files.
